---
- name: Deploy redis.conf
  become: yes
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    owner: root
    group: root
    mode: "0644"
  notify: restart redis

- name: Ensure Redis service is enabled and started
  become: yes
  systemd:
    name: "{{ redis_service_name }}"
    enabled: true
    state: started

