FEATURE_FLAGS = {
    "ENABLE_TEMPLATE_PROCESSING": True,
    "ENABLE_EXPLORE_DRAG_AND_DROP": True,
    "ALERT_REPORTS": True,
    "DASHBOARD_CROSS_FILTERS": True,
    "DASHBOARD_NATIVE_FILTERS": True,
    "DASHBOARD_RBAC": True,
    "ENABLE_ADVANCED_DATA_TYPE": True,
    "ENABLE_SUPERSET_ANALYTICS": True,

    # MOST IMPORTANT
    "ENABLE_DATASOURCE_API": True,
    "ENABLE_EXPLORER": True,
    "ENABLE_REACT_CRUD_VIEWS": True,
    "ENABLE_SQLLAB": True,
    "ENABLE_SQLLAB_BACKEND_PERSISTENCE": True,
}

SECRET_KEY = "2zgkucKJEAZm6IJvXyk+I9378v5CYYIrMV5FHb6xjx9FbL/iQPIv1eQV"
SQLALCHEMY_DATABASE_URI = "postgresql+psycopg2://superset:superset@postgres:5432/superset"
