# roles/superset/tasks/main.yml

- name: Include tasks to deploy Docker Compose project
  include_tasks: docker.yml

- name: Initialize Superset (db upgrade, admin, init)
  include_tasks: init.yml

- name: Configure database connections via Superset API
  include_tasks: api_databases.yml
