---
#Using Vault would be more secure and proper way.
- hosts: all
  become: yes
  gather_facts: no

  vars:
    user1pass: 'password'
    user2pass: 'password'
    user3pass: 'password'

  tasks:
    - name: Ensure user exists
      user:
        name: user
        state: present
        shell: /bin/bash

    - name: Change user1 password
      user:
        name: user1
        update_password: always
        password: "{{ user1pass | password_hash('sha512') }}"

    - name: Change user2pass password
      user:
        name: user2
        update_password: always
        password: "{{ user2pass | password_hash('sha512') }}"

    - name: Change user3 password
      user:
        name: user3
        update_password: always
        password: "{{ user3pass | password_hash('sha512') }}"

